baseURL = 'https://tribectf.cs.wm.edu'
languageCode = 'en-us'
title = 'TribeCTF 2024'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "registration"
    weight = 2
    url = "registration"
  [[menu.header]]
    name = "challenges"
    weight = 3
    url = "challenges"
  [[menu.header]]
    name = "rules"
    weight = 4
    url = "rules"

[params]
readingTime = false  # Show reading time on post page
published = false  # Show published data on post page
user = "TribeCTF "
hostname = " WM"
  [params.author]
    name = "TribeCTF 2024"
  [params.site]
    name = "TribeCTF 2024"  # Website and RSS feed author
    tagline = "Code, Crack, Conquer!"
    detail = "Join William & Mary's inaugural cybersecurity challenge where code breakers meet ethical hackers, and only the nerdiest will capture all flags."



[[params.social]]
key = 0
name = "Join the conversation on Discord"
url = "https://discord.gg"
target = "_blank"
aria = "Discord Server"

